routes/admin.php
<?php

/*
 *
 *  admin panel
 *
 */


Route::get('test', function(){
    app('Illuminate\Bus\Dispatcher')->dispatch(new \App\Jobs\ImportProducts());
});


Route::get('admin/login', 'Admin\AdminController@getLogin');

Route::get('logout', 'Auth\AuthController@logout');

Route::post('admin/login', 'Admin\AdminController@postLogin');

Route::group(['middleware' => ['admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', ['uses' => 'Admin\AdminController@index', 'as' => 'admin.index']);

    Route::get('json/changevisibility', 'Admin\JsonController@getChangeVisibility');

    Route::get('json/delete', 'Admin\JsonController@getDeleteModel');

    Route::get('json/delete-category-icon', 'Admin\JsonController@deleteCategoryIcon');

    Route::resource('lists', 'Admin\ListsController');

    Route::get('get-users', 'Admin\UserController@ajaxData');

    Route::resource('users', 'Admin\UserController');

    Route::resource('content', 'Admin\ContentController');

    Route::resource('categories', 'Admin\CategoriesController');

    Route::get('get-categories', 'Admin\CategoriesController@ajaxData');

    Route::resource('products', 'Admin\ProductsController');

    Route::get('get-products', 'Admin\ProductsController@ajaxData');

    Route::get('clear-cache', 'Admin\AdminController@clearCache');

    Route::get('translations', 'Admin\TranslationsController@edit');

    Route::post('translations', 'Admin\TranslationsController@save');

    Route::resource('parameters',       'Admin\ParametersController');

    Route::get('json/remove-parameter', 'Admin\ParametersController@removeParameter');

    Route::get('json/remove-parameter-value', 'Admin\ParametersController@removeParameterValue');

    Route::get('json/get-category-parameters',  'Admin\ParametersController@getCategoryParameters');

    Route::resource('orders', 'Admin\OrdersController');

    Route::get('get-orders', 'Admin\OrdersController@ajaxData');
});

routes/frontend.php
<?php

/*
 *
 * FRONTEND
 *
 */


Route::get('/', 'HomeController@index')->name('index');

Route::get('home', function () {
    return redirect('/');
});

Route::get('about', 'HomeController@getAbout')->name('get-about');

//Route::get('products', 'ProductController@getCategories')->name('get-categories');
//Route::get('products/{category_slug}', 'ProductController@getProductsCategory')->name('get-products-category');
Route::get('objects/{object_slug}', 'ProductController@getProduct')->name('get-product');

/*===================================
=            Mail routes            =
===================================*/

Route::post('send-contact-form', 'HomeController@sendContactForm')->name('send-contact-form');
Route::post('send-consultation-form', 'HomeController@sendConsultationForm')->name('send-consultation-form');
/*=====  End of Mail routes  ======*/

/*=====  End of Profile routes  ======*/

//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
Route::get('{slug}', ['uses'=>'ContentController@getBySlug', 'as'=>'content']);

routes/web.php
<?php

/*
 *
 *  photomanager
 *
 */
// upload
Route::group(['middleware' => ['admin']], function () {
    Route::any('photos/upload', 'Admin\PhotosController@upload');
    Route::get('photos/getphotos', 'Admin\PhotosController@getJSONPhotos');
    Route::get('photos/changesort', 'Admin\PhotosController@changesort');
    Route::get('photos/delete/{id}', 'Admin\PhotosController@destroy');
});

/*
 * Route patterns
 *
 */
Route::pattern('id', '\d+');
Route::pattern('hash', '[a-z0-9]+');
Route::pattern('hex', '[a-f0-9]+');
Route::pattern('uuid', '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}');
Route::pattern('base', '[a-zA-Z0-9]+');
Route::pattern('slug', '[a-z0-9-]+');
Route::pattern('username', '[a-z0-9_-]{3,16}');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $casts = [
        'params' => 'collection',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'open_password', 'phone', 'address', 'params'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'open_password',
    ];

    public function isManager()
    {
        // this looks if is manager in rights column in your users table
        if ($this->rights == 2) return true;
        return false;
    }

    public function isAdmin()
    {
        // this looks if is admin in rights column in your users table
        if ($this->rights == 1) return true;
        return false;
    }

    public function getCakePhpPassword()
    {
        return $this->open_password;
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Partner;
use App\Models\Products;
use App\Models\Vendor;
use Illuminate\Http\Request;
use App\Models\User;

use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    public function index()
    {
        return view('admin.users.index');
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajaxData()
    {
        $query = User::query();

        return self::datatablesCommon($query)
            ->make(true);
    }

    public function create()
    {
        return view('admin.users.edit')->with($this->common());
    }

    public function store(Request $request)
    {
        $rules = array(
            'name'          => 'required',
            'email'         => 'required',
        );

        $this->validate($request, $rules);

        return $this->save($request, null);
    }

    public function edit($id)
    {
        $data['data'] = User::find($id);
        return view('admin.users.edit', $data)->with($this->common());
    }

    public function save(Request $request, $id)
    {

        if (!isset($id)) {
            $data = new User();
        } else {
            $data = User::find($id);
        }

        $params = [
                'company' => $request->company,
                'fisc' => $request->fisc,
                'bank' => $request->bank,
                'bank_account' => $request->bank_account,
                'tva' => $request->tva,
                'fax' => $request->fax,
        ];

        $data->params = $params;

        $data->name                 = $request->name;
        $data->email                = $request->email;
        $data->phone                = $request->phone;
        $data->rights               = $request->rights;
        $data->enabled              = $request->enabled;
        $data->address              = $request->address;

        if ($request->password != '') {
            $data->password = bcrypt($request->password);
        }
        $data->save();

        // redirect
        Session::flash('message', trans('common.saved'));
        return redirect('admin/users');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $rules = array(
            'name'           => 'required',
            'email'          => 'required',
        );

        $this->validate($request, $rules);

        return $this->save($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        Session::flash('message', trans('common.deleted'));
        return back();
    }

    public function common()
    {
        return [];
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.body')
@section('title', 'Редактирование пользователя')
@section('centerbox')
    <div class="page-header">
        <h1> <a href="{{ url('admin/users') }}"> Пользователи</a>
            <small><i class="ace-icon fa fa-angle-double-right"></i> Редактирование</small> </h1>
    </div>

    @include('admin.partials.errors')

    @if(!isset($data))
        {{ Form::open(['url' => 'admin/users', 'class' => 'form-horizontal']) }}
    @else
        {{ Form::open(['url' => 'admin/users/' . $data->id, 'method' => 'put', 'class' => 'form-horizontal']) }}
    @endif

    <div class="form-actions">
        <div class="row center">
            <div class="col-sm-2">
                <button id="submit_button1" type="submit" class="btn  btn-success btn-block btn-responsive" ><i class="ace-icon fa fa-floppy-o  bigger-120"></i> Сохранить </button>
            </div>
        </div><!-- /.row -->
    </div><!-- /.form-actions -->

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                {{ Form::label('name', 'Имя', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('name', (isset($data->name) ? $data->name : old('name')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('email', 'Email', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('email', (isset($data->email) ? $data->email : old('email')), array('class' =>
                    'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="margin-top-35"></div>

            <div class="form-group">
                {{ Form::label('company', 'Название компании', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('company', (isset($data->params['company']) ? $data->params['company'] : old('company')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('fisc', 'Фискальный код', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('fisc', (isset($data->params['fisc']) ? $data->params['fisc'] : old('company')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('bank', 'Банк', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('bank', (isset($data->params['bank']) ? $data->params['bank'] : old('company')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('bank_account', 'Текущий счет', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('bank_account', (isset($data->params['bank_account']) ? $data->params['bank_account'] : old('bank_account')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('tva', 'НДС', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('tva', (isset($data->params['tva']) ? $data->params['tva'] : old('company')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('fax', 'Факс', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('fax', (isset($data->params['fax']) ? $data->params['fax'] : old('company')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('phone', 'Телефон', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('phone', (isset($data->phone) ? $data->phone : old('phone')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('address', 'Адрес', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('address', (isset($data->address) ? $data->address : old('address')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>

            <div class="margin-top-35"></div>

            <div class="form-group">
                {{ Form::label('password', 'Новый пароль', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::text('password', old('password'), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>
            <div class="form-group">
                {{ Form::label('comment', 'Комментарий', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::textarea('comment', (isset($data->comment) ? $data->comment : old
                    ('comment')), array('class' => 'col-sm-11 col-xs-12')) }}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                {{ Form::label('rights', 'Роль', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::select('rights', ['0' => 'Пользователь', '1' => 'Администратор'], (isset($data->rights) ? $data->rights : old('rights')), ['class' => 'col-sm-9']) }}
                </div>
            </div>
            <div class="form-group">
                {{ Form::label('enabled', 'Активный', ['class'=>'col-sm-3 control-label no-padding-right']) }}
                <div class="col-sm-9">
                    {{ Form::select('enabled', ['1' => 'Да', '0' => 'Нет'], (isset($data->enabled) ? $data->enabled : old('enabled')), ['class' => 'col-sm-9']) }}
                </div>
            </div>
        </div>
    </div><!-- row -->

    {{ Form::close() }}

@endsection

@section('scripts')

    @include('admin.partials.chosen')

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.body')
@section('title', 'Список пользователей')

@section('centerbox')
    <div class="page-header">
        <h1> Администрирование <small><i class="ace-icon fa fa-angle-double-right"></i> Пользователи </small> </h1>
    </div>

    <a class="btn btn-success" href="{{ route('admin.users.create') }}" title="Создать">
        <i class="ace-icon fa fa-plus-square-o bigger-120"></i>
        Создать
    </a>

    <div class="row">
        <div class="col-xs-12">
            <div class="clearfix"><div class="pull-right tableTools-container"></div></div>
            <div class="table-header"> Список пользователей </div>

            <table id="dynamic-table" class="table table-striped table-bordered table-hover dataTable">
                <thead>
                <tr>
                    <th align="center">ID</th>
                    <th align="center">ФИО</th>
                    <th align="center">Email</th>
                    <th align="center">Создан</th>
                    <th align="center"><i class="fa fa-cogs"></i></th>
                </tr>
                </thead>
                <tbody bgcolor="white"></tbody>
            </table>
        </div><!-- /.col-xs-12 -->
    </div><!-- /.row -->
@stop
@section('scripts')

    <script>
        var columns = [
            { data : 'id' },
            { data : 'name' },
            { data : 'email' },
            { data : 'created_at' },
            { data : 'actions', className : 'center' }
        ];
    </script>

    @include('admin.partials.datatable-init-ajax', ['ajax' => 'admin/get-users'])

@endsection

resources/views/admin/users/list-user.blade.php
@extends('admin.body')
@section('title', $title)
@section('centerbox')
    <div class="page-header">
        <h1> {{ $title }} <small><i class="ace-icon fa fa-angle-double-right"></i> {{ $desc }} </small> </h1>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-success @if(isset($modalbox) && $modalbox) modalbox @endif" href="{{ URL::to('admin/users/create') }}">
                <i class="ace-icon fa fa-plus-square-o  bigger-120"></i>
                Создать
            </a>

            @yield('listbuttons')

            <div class="clearfix"><div class="pull-right tableTools-container"></div></div>
            <div class="table-header"> {{ $desc }} </div>

            <table id="dynamic-table" class="table table-striped table-bordered table-hover dataTable">
                <thead>
                <tr>
                    <th class="center">
                        <label class="pos-rel"><input type="checkbox" class="ace" /><span class="lbl"></span></label>
                    </th>
                    <th align="center">ID</th>
                    @foreach($fields as $field)
                        <th align="center">{{ $field }}</th>
                    @endforeach

                    <th align="center"><i class="menu-icon fa fa-cogs"></i> </th>
                </tr>
                </thead>
                <tbody bgcolor="white">
                @foreach($data as $d)
                    <tr class="">
                        <td class="center">
                            <label class="pos-rel"><input type="checkbox" class="ace" /><span class="lbl"></span></label>
                        </td>
                        <td align="right">
                            {{ $d->id }}
                        </td>
                        <?php $i = 0; ?>
                        @foreach($fields as $key => $field)
                            <?php $i++; ?>
                            @if($i == 1)
                                <td align="left">
                                    <a title="Редактирование" href="{{ URL::to('admin/users/'.$d->id.'/edit') }}"
                                       class="@if(isset($modalbox) && $modalbox) modalbox @endif">{{ $d->$key }}</a>
                                </td>
                                @continue
                            @endif
                            <td align="center">
                                {{ $d->$key }}
                            </td>
                        @endforeach

                        <td align="center">
                            <div class="action-buttons">
                                <a href="{{ URL::to('admin/'.$model.'/'.$d->id.'/edit') }}" class="yellow @if(isset($modalbox) && $modalbox) modalbox @endif"><i class="ace-icon fa fa-pencil bigger-130"></i></a>
                                {{ Form::open(array('url' => 'admin/' . $model . '/' . $d->id, 'class' => 'pull-right')) }}
                                {{ Form::hidden('_method', 'DELETE') }}
                                {{ Form::button('<i class="ace-icon fa fa-trash-o bigger-130"></i>', ['type' => 'submit', 'class' => 'red deletebutton']) }}
                                {{ Form::close() }}
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div><!-- /.col-xs-12 -->
    </div><!-- /.row -->
@endsection

@section('styles')
    {{HTML::style('ace/assets/css/dataTables.responsive.css')}}
@endsection

@section('scripts')

    @include('admin.partials.datatable-init')

    @include('admin.partials.visibility')

@append